parameters:
#    bionic_university_hr.example.class: BionicUniversity\HRBundle\Example

services:
#    bionic_university_hr.example:
#        class: %bionic_university_hr.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
