parameters:
#    hr.example.class: BionicUniversity\HRManagementBundle\Example

services:
#    hr.example:
#        class: %hr.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
